package com.xworkz.collections;

import java.util.*;

public class CollectionAdd {

	public static void main(String[] args) {

		Collection collection = new ArrayList();

		collection.add("Yugadi");
		collection.add("Sankranthi");
		collection.add("Deepavali");
		collection.add("Dasara");
		collection.add("Rama Navami");
		collection.add("Ganesha Chathurthi");
		collection.add("Christmas");
		collection.add("Holi");
		collection.add("Raksha BAndhan");
		collection.add("Lakshmi Pooja");
		collection.add("Thulasi Madve");
		collection.add("Varamahalakshmi");
		collection.add("Shivarathri");
		collection.add("Bakrid");
		collection.add("Id Milad");
		collection.add("Mahalaya amavasye");
		collection.add("Surya Grahana");
		collection.add("Chandra grahana");
		collection.add("Sarasvathi pooje");
		collection.add("Bheemana Amavasye");
		collection.add("Gouri Habba");
		collection.add("Balipadyami");
		collection.add("Shri Krishna Janmashtami");
		collection.add("Govu Pooje");
		collection.add("Maari Habba");
		collection.add("");
		collection.add("");
		collection.add("");
		collection.add("");
		collection.add("");
		collection.add("");
		collection.add("");
		collection.add("");
		collection.add("");
		collection.add("");
		collection.add("");
		collection.add("");
		collection.add("");
		collection.add("");
		collection.add("");
		collection.add("");
		collection.add("");
		collection.add("");
		collection.add("");
		collection.add("");
		collection.add("");
		collection.add("");
		collection.add("");
		collection.add("");
		collection.add("");
		collection.add("");
		collection.add("");
		collection.add("");
		collection.add("");
		collection.add("");
		collection.add("");
		collection.add("");
		collection.add("");
		collection.add("");
		collection.add("");

		collection.add("Rajkumar");// actors
		collection.add("Vishnuvardhan");
		collection.add("Dwarkish");
		collection.add("Ambarish");
		collection.add("Ravichandran");
		collection.add("Shankar Nag");
		collection.add("Ananth Nag");
		collection.add("Jai Jagdeesh");
		collection.add("Prakash Rai");
		collection.add("Ramesh Arvind");
		collection.add("Shashikumar");
		collection.add("Jaggesh");
		collection.add("Sudeep");
		collection.add("Sai Kumar");
		collection.add("Upendra");
		collection.add("Sharan");
		collection.add("Diganth");
		collection.add("Sathish Neenasam");
		collection.add("Ajay Rao");
		collection.add("Chiranjeevi Sarja");
		collection.add("Vijay Raghavendra");
		collection.add("Rakshit Shetty");
		collection.add("Harish Raj");
		collection.add("Naveen Krishna");
		collection.add("Kishor Kumar");
		collection.add("Srinath");
		collection.add("Lokesh");
		collection.add("ShivarajKUmar");
		collection.add("Puneeth Rajkumar");
		collection.add("Darshan Thoogudeep");
		collection.add("Ganesh");
		collection.add("Yash");
		collection.add("Srimuruli");
		collection.add("Adithya");
		collection.add("Prajwal Devaraj");
		collection.add("Srinagr Kitty");
		collection.add("Dhananjaya");
		collection.add("Srujan Lokesh");
		collection.add("Komal Kumar");
		collection.add("Yogesh");
		collection.add("Vijay Suriya");
		collection.add("Rakesh Adiga");
		collection.add("Prem");
		collection.add("Prem Kumar");
		collection.add("Nirup Bhandari");
		collection.add("J. Karthik");
		collection.add("Sanchari Vijay");
		collection.add("Arun Sagar");
		collection.add("Sri Muruli");
		collection.add("Charan Raj");
		collection.add("Tom Hanks");
		collection.add("Robert De Niro");
		collection.add("Jackie Chan");
		collection.add("Sean Pennk");
		collection.add("Alec Baldwin");
		collection.add("Piecrce Brosnan");
		collection.add("Clint Eastwood");
		collection.add("Sylvester Stallone");
		collection.add("Stark");
		collection.add("Stanley Tucci");

		collection.add("Kannada");// Languages
		collection.add("Spanish");
		collection.add("Mandarin Chinese");
		collection.add("Bengali");
		collection.add("Hindi");
		collection.add("Portuguese");
		collection.add("Russian");
		collection.add("Japanese");
		collection.add("German");
		collection.add("Chinese,wu");
		collection.add("Korean");
		collection.add("French");
		collection.add("Vietnamese");
		collection.add("Marathi");
		collection.add("Telugu");
		collection.add("Turkish");
		collection.add("French");
		collection.add("Javanese");
		collection.add("Italian");
		collection.add("Egyptian Arabic");
		collection.add("Gujarati");
		collection.add("Iranian Persian");
		collection.add("Bhojpuri");
		collection.add("Southern Min");
		collection.add("Hakka");
		collection.add("Jin Chinese");
		collection.add("Hausa");
		collection.add("Indonesian");
		collection.add("Polish");
		collection.add("Yoruba");
		collection.add("Xiang Chinese");
		collection.add("Malayalam");
		collection.add("Odia");
		collection.add("Maithili");
		collection.add("Burmese");
		collection.add("Sunda");
		collection.add("Sudanese Arabic");
		collection.add("Algerian Arabic");
		collection.add("Moroccan Arabic");
		collection.add("Ukrainian");
		collection.add("Igbo");
		collection.add("Northern Uzbek");
		collection.add("Sindhi");
		collection.add("North Levantine Arabic");
		collection.add("Romanian");
		collection.add("Tagalog");
		collection.add("Dutch");
		collection.add("Saidi Arabic");
		collection.add("khandi");
		collection.add("Malvi");
		collection.add("Sadri");
		collection.add("Mewari");
		collection.add("Wagdi");
		collection.add("Lambadi");
		collection.add("Bhilodi");
		collection.add("Harauti");
		collection.add("Nepali");
		collection.add("Gondi");
		collection.add("Baghel Khandi");
		

		// movies
		movie.add("Unhinged");
		movie.add("Like a Boss");
		movie.add("Bloodshot");
		movie.add("Emma");
		movie.add("Trolls World Tour");
		movie.add("Gretel & Hansel");
		movie.add("Scoob!");
		movie.add("Brahms: The Boy II");
		movie.add("The Turning");
		movie.add("The Way Back");
		movie.add("La Belle Epoque");
		movie.add("I Still Believe");
		movie.add("The Hunt");
		movie.add("Las Pildoras De Mi Novio");
		movie.add("Mission: Impossible 2 ");
		movie.add("Gladiator");
		movie.add("Cast Away");
		movie.add("What Women Want");
		movie.add("Dinosaur");
		movie.add("How the Grinch Stole Christmas");
		movie.add("Meet the Parents");
		movie.add("The Perfect Storm");
		movie.add("X-Men");
		movie.add("What Lies Beneath");
		movie.add("Avengers: Endgame");
		movie.add("Star Wars: The Force Awakens");
		movie.add("Avengers: Infinity War");
		movie.add("Jurassic World");
		movie.add("The Lion King");
		movie.add("The Avengers");
		movie.add("Furious 7");
		movie.add("Frozen II");
		movie.add("Avengers: Age of Ultron");
		movie.add("Black Panther");
		movie.add("Harry Potter and the Deathly Hallows  Part 2");
		movie.add("Star Wars: The Last Jedi");
		movie.add("Jurassic World: Fallen Kingdom");
		movie.add("Frozen");
		movie.add("Beauty and the Beast");
		movie.add("Incredibles 2");
		movie.add("The Fate of the Furious");
		movie.add("Iron Man 3");
		movie.add("gita govida");
		movie.add("comrade");
		collection.add("");
		collection.add("");
		collection.add("");
		collection.add("");
		collection.add("");
		collection.add("");
		collection.add("");
		collection.add("");
		collection.add("");
		collection.add("");
		collection.add("");
		collection.add("");
		collection.add("");
		collection.add("");
		collection.add("");
		collection.add("");
		collection.add("");
		collection.add("");
		collection.add("");
		collection.add("");
		collection.add("");
		collection.add("");
		collection.add("");
		collection.add("");
		collection.add("");
		collection.add("");
		collection.add("");
		collection.add("");
		collection.add("");
		collection.add("");
		collection.add("");
		collection.add("");
		collection.add("");
		collection.add("");
		
		//webseries
		collection.add("Capitol Hill");
		collection.add("Crash Course");
		collection.add("Copy & Pastry");
		collection.add("Consolevania");
		collection.add("Compulsions");
		collection.add("Community ");
		collection.add("Coming Out");
		collection.add("Comedians in Cars Getting Coffee");
		collection.add("CollegeHumor");
		collection.add("Codefellas");
		collection.add("Class of 2017");
		collection.add("Clutch");
		collection.add("Classic Alice");
		collection.add("Clark and Michael");
		collection.add("Chop Socky Boom");
		collection.add("Childrens Hospital");
		collection.add("Chelsea Does");
		collection.add("Chelsea");
		collection.add("Chateau Laurier");
		collection.add("Chance");
		collection.add("Chad Vader");
		collection.add("CELL");
		collection.add("Castlevania");
		collection.add("Carpool Karaoke");
		collection.add("Carmilla");
		collection.add("Titans Season 3");
		collection.add("Inside Edge Season 3");
		collection.add("Lost in Space Season 3");
		collection.add("Hiccups & Hookups");
		collection.add("Hawkeye");
		collection.add("Cowboy Bebop Season 1");
		collection.add("The Wheel of Time");
		collection.add("Star Trek: Discovery Season 4");
		collection.add("Special Ops 1.5");
		collection.add("Call My Agent: Bollywood");
		collection.add("Little Things Season 4");
		collection.add("Succession Season 3");
		collection.add("House of Secrets: The Burari");
		collection.add("Break Point");
		collection.add("Foundation Season 1");
		collection.add("Kota Factory Season 2");
		collection.add("Star Wars: Visions Season 1");
		collection.add("Squid Game Season 1");
		collection.add("The Last Man Season 1");
		collection.add("Mumbai Diaries 26/11");
		collection.add("Money Heist Season 5");
		collection.add("The Empire Season 1");
		collection.add("What If? Season 1");
		collection.add("Feels Like Ishq Season 1");
		collection.add("Ted Lasso Season 2");
		collection.add("Never Have I Ever Season 2");
		collection.add("Ray Season 1");
		collection.add("Loki Season 1");
		collection.add("The Family Man Season 2");
		collection.add("kimit su yaiba");
		collection.add("attack of taitan");
		collection.add("lost in space");
		collection.add("charnobly");
		collection.add("dark");
		collection.add("streger things");

		System.out.println(" No of web series:" + collection.size());
		collection.remove("Cowboy Bebop Season 1");
		System.out.println(" No of web series After Delete:" + collection.size());
		
		//cities
		collection.add("aurangabad");
		collection.add("amalner");
		collection.add("pune");
		collection.add("jalna");
		collection.add("ajintha");
		collection.add("paithan");
		collection.add("maysor");
		collection.add("bangloare");
		collection.add("dilhi");
		collection.add("kolkatta");
		collection.add("paris");
		collection.add("punjab");
		collection.add("amritsur");
		collection.add("jaypur");
		collection.add("nashik");
		collection.add("patayya");
		collection.add("goa");
		collection.add("huballi");
		collection.add("kannad");
		collection.add("dhule");
		collection.add("40 gav");
		collection.add("raj kot");
		collection.add("ahmdabad");
		collection.add("gandhi nagar");
		collection.add("surat");
		collection.add("mumbai");
		collection.add("rajpal");
		collection.add("bhuneshwar");
		collection.add("manglore");
		collection.add("abu dabi");
		collection.add("kolhapur");
		collection.add("ichalkaranji");
		collection.add("sangli");
		collection.add("miraj");
		collection.add("dharwad");
		collection.add("shiratwad");
		collection.add("nipani");
		collection.add("chikurdi");
		collection.add("ghokag");
		collection.add("jamakahand");
		collection.add("shirdi");
		collection.add("gangapur");
		collection.add("bhosawal");
		collection.add("shirpur");
		collection.add("airandol");
		collection.add("jalgav");
		collection.add("fagne");
		collection.add("mannad");
		collection.add("parbhani");
		collection.add("latur");
		collection.add("agra");
		collection.add("ranchi");
		collection.add("chiru");
		collection.add("nepal");
		collection.add("kolhar");
		collection.add("kur");
		collection.add("madkiri");
		collection.add("virajpet");
		collection.add("ooty");
		collection.add("mandya");
		
		System.out.println(" No of cities:" + collection.size());
		collection.remove("kolhapur");
		System.out.println(" No of cities After Delete:" + collection.size());
		
		collection.add("");// Sweets
		collection.add("Arisa Pitha");
		collection.add("Apple Halwa");
		collection.add("Balushahi");
		collection.add("Boondi");
		collection.add("Gajar ka halwa");
		collection.add("Ghevar");
		collection.add("Gulab jamun");
		collection.add("Imarti");
		collection.add("Jalebi");
		collection.add("Kaju katli");
		collection.add("Kalakand");
		collection.add("Kheer");
		collection.add("Khirmohan");
		collection.add("Kulfi");
		collection.add("Laddu");
		collection.add("Lassi");
		collection.add("Motichoor laddu");
		collection.add("Malpua");
		collection.add("Nankhatai");
		collection.add("Petha");
		collection.add("Phirni");
		collection.add("Rabri");
		collection.add("Sheera");
		collection.add("Singori");
		collection.add("Sohan halwa");
		collection.add("Sohan papdi, pateesa");
		collection.add("Amriti");
		collection.add("Cham cham");
		collection.add("Chandrapuli");
		collection.add("Chhena gaja");
		collection.add("Chhena jalebi");
		collection.add("Chhena Jhili");
		collection.add("Chhena kheeri");
		collection.add("Chhena poda");
		collection.add("Chuda Ghasa");
		collection.add("Coconut Barfi");
		collection.add("Kheer sagar");
		collection.add("Ledikeni");
		collection.add("Lyangcha");
		collection.add("Malapua");
		collection.add("Mihidana");
		collection.add("Misti doi");
		collection.add("Pantua");
		collection.add("Pithe");
		collection.add("Puri Khaja");
		collection.add("Rabri	");
		collection.add("Rasabali");
		collection.add("Ras malai");
		collection.add("Rasgulla");
		collection.add("Sandesh");
		collection.add("Sirir naru");
		collection.add("Ada");
		collection.add("Adhirasam");
		collection.add("Bandar laddu");
		collection.add("Chikki");
		collection.add("Dharwad Pedha");
		collection.add("Double ka Meetha");
		collection.add("god pole");
		collection.add("god bhat");
		collection.add("fafad");

		System.out.println(" No of Sweets:" + collection.size());
		collection.remove("Chhena jalebi");
		System.out.println(" No of Sweets After delete:" + collection.size());
		
		// Bikes
		collection.add("Bajaj Dominar 400");
		collection.add("Bajaj Pulsar NS 125");
		collection.add("Bajaj Pulsar NS160");
		collection.add("Bajaj Platina 100");
		collection.add("Bajaj Pulsar F250	");
		collection.add("Bajaj Pulsar 180	");
		collection.add("Bajaj Chetak");
		collection.add("Bajaj CT110");
		collection.add("Bajaj Dominar 250");
		collection.add("Bajaj Avenger Cruise 220");
		collection.add("Bajaj Pulsar N250");
		collection.add("Bajaj Platina 110 H Gear");
		collection.add("Bajaj Avenger Street 160");
		collection.add("Bajaj Platina 110");
		collection.add("Bajaj NS250");
		collection.add("Bajaj Avenger 400");
		collection.add("KTM RC 200");
		collection.add("KTM 200 Duke");
		collection.add("KTM 125 Duke");
		collection.add("KTM RC 390");
		collection.add("KTM 390 Duke");
		collection.add("KTM 250 Duke");
		collection.add("KTM RC 125 ");
		collection.add("2021 KTM RC 125");
		collection.add("2021 KTM RC 200");
		collection.add("KTM 390 Adventure");
		collection.add("pulsar 150");
		collection.add("KTM 250 Adventure");
		collection.add("Royal Enfield Classic 350");
		collection.add("TVS Jupiter 125");
		collection.add("TVS Apache RTR 160");
		collection.add("Yamaha YZF R15 V3");
		collection.add("TVS Apache RTR 160 4V");
		collection.add("Yamaha MT 15");
		collection.add("TVS Sport");
		collection.add("Hero Splendor Plus");
		collection.add("TVS Jupiter");
		collection.add("TVS XL100");
		collection.add("TVS Apache RTR 200 4V");
		collection.add("TVS Apache RR 310");
		collection.add("TVS Scooty Pep Plus");
		collection.add("TVS Apache RTR 180");
		collection.add("TVS Star City Plus");
		collection.add("TVS Scooty Zest");
		collection.add("TVS NTORQ 125");
		collection.add("TVS Radeon");
		collection.add("TVS iQube Electric");
		collection.add("TVS Raider");
		collection.add("Yamaha YZF R15 V3");
		collection.add("TVS Apache RTR 160");
		collection.add("Jawa 42");
		collection.add("Jawa Perak");
		collection.add("Jawa");
		collection.add("Jawa Cruiser");
		collection.add("Bajaj Pulsar 150");
		collection.add("Bajaj Pulsar NS200");
		collection.add("Bajaj Pulsar 220 F");
		collection.add("Bajaj Pulsar RS200");
		collection.add("Bajaj Pulsar 125 Neon");
		collection.add("Bajaj CT100");
		
		//cars
		collection.add("Audi 255d");
		collection.add("Audi 450d");
		collection.add("Audi 220d");
		collection.add("Audi 250d");
		collection.add("Jaguar E-Pace R Dynamic HSE SUV 2021");
		collection.add("Jaguar E-Pace R-Dynamic S SU");
		collection.add("Jaguar E-Pace R-Dynamic S SUV 2019");
		collection.add("Jaguar E-Pace R Dynamic SUV");
		collection.add("Jaguar F-Pace Prestige SUV 20");
		collection.add("Jaguar F Pace Prestige SUV 2020");
		collection.add("Jaguar F-Pace R-Sport SUV 2018");
		collection.add("Jaguar F-Pace S SUV 2021");
		collection.add("Jaguar F-Type Convertible 2017");
		collection.add("Jaguar F-Type Base Convertible 2017");
		collection.add("Jaguar F-Type Convertible 2018");
		collection.add("Jaguar F-Type R Dynamic Convertible 2018");
		collection.add("Jaguar F-Type R Dynamic Coupe 2019");
		collection.add("Mercedes AMG GT AMG GT Roadster 2018");
		collection.add("Mercedes-Benz A-Class 200 Sedan 2019");
		collection.add("Mercedes-Benz A-Class 220 Sedan 2019");
		collection.add("Mercedes-Benz A-Class A160...");
		collection.add("Mercedes-Benz A Class Hatchback 2019");
		collection.add("Mercedes-Benz AMG GT Coupe 2020");
		collection.add("Mercedes-Benz AMG GT Coupe 2017");
		collection.add("Mercedes-Benz AMG GT Roadster 2019");
		collection.add("Mercedes-Benz B-Class B200 Sport Mini...");
		collection.add("Mercedes-Benz B-Class Electric Drive...");
		collection.add("Mercedes-Benz B Class Hatchback 2018");
		collection.add("Mercedes-Benz C-Class AMG C43 Coupe 2017");
		collection.add("Volvo C30 Hatchback 2008");
		collection.add("Volvo S60 Cross Country Summum Sedan...");
		collection.add("Volvo S60 R Design Sedan 2019");
		collection.add("Volvo S60 R-Design Sedan 2019");
		collection.add("Volvo S60 Recharge Polestar Sedan 2021");
		collection.add("Volvo S60 Summum Sedan 2014");
		collection.add("Volvo S60 T5 Sedan 2018");
		collection.add("Aston Martin Cygnet Hatchback ");
		collection.add("Aston Martin DB11 Coupe 2016");
		collection.add("Aston Martin DB11 Coupe 2017");
		collection.add("Aston Martin DB11 Coupe ");
		collection.add("Aston Martin DBS Volante Conv");
		collection.add("Aston Martin DB9 Coupe 2016");
		collection.add("Aston Martin DB11 Volante Con");
		collection.add("Aston Martin DB11 Volante Con");
		collection.add("Acura ILX Premium Sedan 2019");
		collection.add("Audi A1 Ambition Hatchback 201");
		collection.add("Audi A1 Sportback Hatchback 2015");
		collection.add("Audi A1 Sportback S Line Hatchback 2019");
		collection.add("Audi A1 Sport Hatchback 2016");
		collection.add("Audi A3 Ambition Convertible 201");
		collection.add("Audi A3 Ambition Hatchback 2014");
		collection.add("Audi A3 Attraction Convertible 2014");
		collection.add("Audi A3 E-Tron Premium Plus H");
		collection.add("Audi A3 E-Tron Ambiente Hybrid...");
		collection.add("audi A1");
		collection.add("Audi A2");
		collection.add("Audi A3");
		collection.add("Audi A4");
		collection.add("Audi A5");
		collection.add("Audi A6");

		// Lipsticks
		collection.add("Gloss Lipsticks");
		collection.add("Lipstick Stains");
		collection.add("Long-Wearing");
		collection.add("Matte Lipsticks");
		collection.add("Moisturizing Lipsticks");
		collection.add("Pearl/Frosted Lipsticks");
		collection.add("Sheer/Satin Lipsticks");
		collection.add("Black Honey");
		collection.add(" Lip Pencil");
		collection.add("NARS Semi Matte");
		collection.add("Chanel Rouge Allure ");
		collection.add("MAC Red Lipstick");
		collection.add("Revlon Super Lustrous ");
		collection.add("Tom Ford Lip Color");
		collection.add("NARS Lipstick");
		collection.add("GIORGIO ARMANI BEAUTY Rouge");
		collection.add("Brown by Bobbi Brown");
		collection.add("Longwear Fluid Lip Color");
		collection.add("CHARLOTTE TILBURY");
		collection.add("DIOR Rouge Dior Lipstick");
		collection.add("M.A.C Lipstick Matte");
		collection.add("SEPHORA festival Cream Lip ");
		collection.add("Exaltée by Chanel");
		collection.add("Rimmel London Lip Stick");
		collection.add("DIOR Rouge Dior Lipstick");
		collection.add("M.A.C Viva Glam Lipstick");
		collection.add("Tom Ford Lip Color");
		collection.add("Lancome ROUGE IN LOVE");
		collection.add("Tom Ford Lip Color");
		collection.add("LOréal Paris Colour Riche Lipstick");
		collection.add("Rimmel London Lasting Finish");
		collection.add("Kate Lipstick");
		collection.add("Maybelline Color ");
		collection.add("Covergirl Lip Perfection Lipstick");
		collection.add("New Nudes Sheer Gel Lipstick");
		collection.add("ESTÉE LAUDER Pure Color Envy Sculpting Lipstick");
		collection.add("Shiseido Lipstick");
		collection.add("LIPSTICK QUEEN Medieval Lipstick");
		collection.add("CONVERTIBLE COLOR");
		collection.add("SHINE FEVER ");
		collection.add("Ruby Woo by M.A.C.");
		collection.add("Black Honey Almost Lipstick");
		collection.add("M.A.C Lip Penci");
		collection.add("Lady Danger by M.A.C.");
		collection.add("Pirate by Chanel");
		collection.add("Schiap by NARS");
		collection.add("Spice by M.A.C.");
		collection.add("red");
		collection.add("Brown Suga Babe ");
		collection.add("Lip Gloss");
		collection.add("Zolani K");
		collection.add("Satin");
		collection.add("Creamy");
		collection.add("Matte");
		collection.add("Lip Stains or Tints");
		collection.add("Glossy");
		collection.add("metallic");
		collection.add("Tinted Lip Balm");
		collection.add("Lip Liner");
		collection.add("Cream Lipsticks");

		System.out.println(" No of Lipstick:" + collection.size());
		collection.remove("CHARLOTTE TILBURY");
		System.out.println(" No of Lipstick After delete:" + collection.size());

		System.out.println(collection.size());

	}

}
